application: hw3-cloud-comp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: services.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
